controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#POUR REDIRIGER VERS HOME DIRECTEMENT GRÂCE A MON CONTROLLER
index_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: home
        permanent: true
        
#Pour l'erreur 404
error_404:
    path: /error/404
    controller: App\Controller\ErrorController::page404
